altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  fadb1550-d114-4d2d-a728-a92889803662:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-04T13:55:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4c9a8c79-3122-450b-b4ee-114cbc9fdd6a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 623405db-f522-4c77-bc80-d7c2d2949cb6
        userCondition: null
fs: media
handle: lottie
name: Lottie
sortOrder: 2
subpath: lottie
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
