altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  720a92a5-6d66-4567-be1c-1779e33d2658:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-04T13:55:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7df09ca7-7d93-45c2-9856-a3d76d85065e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 80bdce88-4ea4-4482-a612-429976561319
        userCondition: null
fs: media
handle: rive
name: Rive
sortOrder: 3
subpath: rive
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
