dateModified: 1759920739
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - link
      type: native
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: d81e0ca8-0443-4c79-a338-14e2c1fc8687
            values:
              - bd99645a-4524-40e4-83dc-c6b12e023bab # Global
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      defaultViewMode: cards
      key: 'custom:6d0e2f9b-417a-4d0c-b23f-affe43c388c0'
      label: 'Global Info'
      tableAttributes: '-'
      type: custom
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: true
      key: singles
      tableAttributes:
        - status
        - link
      type: native
    -
      heading: Core
      key: 'heading:3ccc79f3-7502-4032-a7c1-7f2ba09a67b5'
      type: heading
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 5690305a-9541-42b2-9e20-e0f68d6f7e30
            values:
              - cdad2202-5d55-49ba-995e-962503f5887f # Home
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      defaultViewMode: cards
      key: 'custom:bef75f27-face-4b86-af9e-61d96538bfed'
      label: Home
      tableAttributes: '-'
      type: custom
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\TypeConditionRule
            operator: in
            uid: f29420f6-ff81-45df-a84d-d52359ee48ac
            values:
              - 70367baf-8815-4efc-a9e3-91985c8ae6d9 # Selection Guide
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      key: 'custom:9c92fe8d-5b37-4bef-8840-ea52e030eefa'
      label: 'Motion Tracking Selection Guide'
      tableAttributes: '-'
      type: custom
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:c4b4f50d-7d62-4a4c-bbf8-7aae00fd82c7' # Pages
      tableAttributes:
        - status
        - uri
      type: native
    -
      heading: Articles
      key: 'heading:374f7794-9d28-4711-b349-970143ffa9b6'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:6ba54824-1c3f-454f-8830-f6cea379bee4' # Blog Posts
      tableAttributes:
        - status
        - 'field:d390347a-09cf-4b70-a3b4-bc3cca520623' # Category
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:70b2614b-639a-4de2-8c11-3851d36d6f8c' # Blog Categories
      tableAttributes:
        - status
        - link
      type: native
email:
  fromEmail: sales@polhemus.com
  fromName: Polhemus
  replyToEmail: sales@polhemus.com
  template: null
  transportSettings:
    host: $SERVD_SMTP_HOSTNAME
    password: $SERVD_SMTP_PASSWORD
    port: $SERVD_SMTP_PORT
    useAuthentication: '1'
    username: $SERVD_SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  media:
    hasUrls: true
    name: Media
    settings:
      cdnUrlPattern: ''
      customSubfolder: media
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: local/media/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://pom-craft.files.svdcdn.com'
meta:
  __names__:
    0a58e287-e038-4eb7-ab2a-cf4cbdbe013d: 'Page content' # Page content
    2b829e15-a7bd-4ab0-9050-dcdfe44499cf: 'Public Schema' # Public Schema
    2bae9725-9546-4f55-a889-56102191aa89: Navigation # Navigation
    3ff25529-419c-4d4a-8109-16999a22695e: About # About
    5dd08fc8-3ea4-4582-952f-4c0f7ebf409e: Category # Category
    6a4769da-4b45-4cd9-bd0a-a73306768757: Blog # Blog
    6ba54824-1c3f-454f-8830-f6cea379bee4: 'Blog Posts' # Blog Posts
    6c819fc7-3f73-4873-8f0c-5ea322fef1f9: 'Divider type' # Divider type
    6c9778b8-507c-4108-937d-6ceeabf35047: Image # Image
    6d0d3aa4-84be-441d-8fcc-2ab2d6db2503: Polhemus # Polhemus
    6d2e5577-5ded-43c9-96e2-d4fc4c770fe9: Text # Text
    6d2396b1-0d86-4ff3-bd52-6c9411a6eb70: New # New
    7b9364bd-2215-495a-8b0b-2280df887a8b: Media # Media
    7dac7ab3-08a0-4af8-ba7c-cbecd0726f08: Simple # Simple
    8d255be3-3a84-415e-9754-056197c08705: Rive # Rive
    9d082133-4710-4468-ab39-80db8c9fcf59: Code # Code
    9d42aa56-4a66-4d0b-b8a9-84a4cb387788: 'Text block' # Text block
    25b2446d-c1d2-4aa1-8184-3147e617f069: Text # Text
    40ce5a4b-d59b-4f98-b3a7-ede4dd81be9b: Markets # Markets
    58ccb571-6c72-449f-8e7b-6f43c5d416b3: Polhemus # Polhemus
    68c38ea9-9638-47de-a1bd-e906024a4a8b: 'Form Chooser' # Form Chooser
    70b2614b-639a-4de2-8c11-3851d36d6f8c: 'Blog Categories' # Blog Categories
    163c895f-0c05-4845-80e2-043b2346d830: Address # Address
    697da4c2-e02f-4f49-9d76-e22609ceda25: Page # Page
    1509c810-f47f-4959-be70-3d5f20b09814: Hero # Hero
    5358db38-27c0-49b4-b9d3-e68326e79da2: Image # Image
    11980d86-8071-47ee-9b88-6c35827df37a: 'Contact Form' # Contact Form
    20554fff-c205-4469-9be6-5280f6865320: 'Footer Sub Nav' # Footer Sub Nav
    70367baf-8815-4efc-a9e3-91985c8ae6d9: 'Selection Guide' # Selection Guide
    544521cd-66c5-4443-bd14-06fae01c2a90: General # General
    0922209d-2911-419e-82cf-b05113a35f6e: Wide # Wide
    97944685-dad4-4391-9435-90fbf757bd94: Military # Military
    a06e695e-af7f-4a1b-84a7-575ec935e293: Video # Video
    a4b949f3-e240-47e9-bc36-b7da59dfa6e1: 'Footer Side Nav' # Footer Side Nav
    b2c4fc8c-2ea4-4985-beb9-5945df837234: Matrix # Matrix
    b5b7bfc5-a39e-4d1a-89be-51f0afeb5ce0: Avatar # Avatar
    b5fb513f-62bf-4e78-abde-b8fd0552c4b7: 'Campaign Monitor' # Campaign Monitor
    b579b454-12bd-4710-a436-c26907141957: Full # Full
    bd99645a-4524-40e4-83dc-c6b12e023bab: Global # Global
    c4b4f50d-7d62-4a4c-bbf8-7aae00fd82c7: Pages # Pages
    c7d2eb61-cdde-4a76-88a9-eb30ddcf155b: Posts # Posts
    c23a2c69-43fc-408a-9f56-8b07c05d6c0b: Toggle # Toggle
    c55ca0a9-4bd6-409b-afd8-c1884dafecd0: Team # Team
    ccc3cb4f-7419-4633-90a2-f7924093b5c8: Lottie # Lottie
    cdad2202-5d55-49ba-995e-962503f5887f: Home # Home
    d1befde0-936f-49fa-98cf-d79c873a21b1: 'Main Nav' # Main Nav
    d4f0917b-edcf-4ef0-a98b-661ff27384ad: Page # Page
    d8b1ff34-56c8-40b1-98b7-9cd055ea6fc3: Products # Products
    d55d172f-8b8f-4bb7-b680-31249981c350: Global # Global
    d390347a-09cf-4b70-a3b4-bc3cca520623: Category # Category
    d419415f-c4a2-454b-b2cd-1f248197dc1a: 'Content Block' # Content Block
    ec5dc9fc-868b-45b1-abf1-49fd49cd5d97: Home # Home
    f6d66912-dcae-41ff-8470-c05de876df65: 'Motion Tracking Selection Guide' # Motion Tracking Selection Guide
    f7576aa3-c155-4b54-82c9-8cb8c93495c9: Callout # Callout
    faf6930d-cd0a-42e5-a3f6-d3153728beb6: 'Footer Nav' # Footer Nav
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  elements-panel:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: 0UOYMI3VK6JQ21A2WHBC8T7K
    schemaVersion: 3.4.10
    settings:
      ajaxTimeout: 10
      alertEmails: null
      defaultDateDisplayType: calendar
      defaultDateTime: null
      defaultDateValueOption: ''
      defaultEmailTemplate: ''
      defaultExportFolder: '@storage/formie-export'
      defaultFileUploadVolume: ''
      defaultFormTemplate: ''
      defaultInstructionsPosition: verbb\formie\positions\AboveInput
      defaultLabelPosition: verbb\formie\positions\AboveInput
      defaultPage: forms
      emptyValuePlaceholder: 'No response.'
      enableBackSubmission: true
      enableCsrfValidationForGuests: true
      enableLargeFieldStorage: false
      enableUnloadWarning: true
      filterIntegrationMapping: true
      includeDraftElementUsage: false
      includeRevisionElementUsage: false
      maxIncompleteSubmissionAge: 30
      maxSentNotificationsAge: 30
      outputConsoleMessages: true
      pdfPaperOrientation: portrait
      pdfPaperSize: letter
      pluginName: Forms
      queuePriority: null
      saveSpam: true
      sendEmailAlerts: false
      sentNotifications: true
      setOnlyCurrentPagePayload: false
      spamBehaviour: showSuccess
      spamBehaviourMessage: ''
      spamEmailNotifications: false
      spamKeywords: ''
      spamLimit: 500
      submissionsBehaviour: all
      useCssLayers: false
      useQueueForIntegrations: true
      useQueueForNotifications: true
      validateCustomTemplates: true
  navigation:
    edition: standard
    enabled: true
    licenseKey: I2EMMQ0YWRACXPS7BDROWGHU
    schemaVersion: 2.1.1
    settings:
      bypassProjectConfig: false
      pluginName: Navigation
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 18ZPKO8IO7F8YPIV9U6016OU
    schemaVersion: 3.0.13
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      adjustFeedmeLogs: ''
      assetsEnvironment: $SERVD_ASSETS_ENVIRONMENT
      assetsEnvironmentOverwrite: ''
      cacheClearMode: full
      clearCachesOnSave: always
      clearCdnCacheWhenAssetChanges: '1'
      disableDynamic: ''
      disableTransforms: ''
      fsMapsEnabled: ''
      imageAutoConversion: avif
      injectCors: ''
      projectSlug: $SERVD_PROJECT_SLUG
      securityKey: $SERVD_SECURITY_KEY
      suppressWarnings: ''
      transformSvgs: 'no'
      useLocalVolumes: false
system:
  edition: solo
  live: true
  name: Polhemus
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: America/New_York
