defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ec5dc9fc-868b-45b1-abf1-49fd49cd5d97 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - /
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  58ccb571-6c72-449f-8e7b-6f43c5d416b3: # Polhemus
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
